### ISSUE TITLE
Integer Support still not fixed

### ISSUE THREAD

**Issue by minijaham** [AntiCores/EasyHomes#7] opened 2020-04-04 18:00 UTC
Hey! I love this plugin, very simple, yet better than any other home plugins, but there is an issue where the form does not open up when you name one of your houses with integer(s) in it. Says that there is an error, and you will have to execute commands like /home tp {name} or /home delete {name}

Please fix this!
Note: duplicate of #5

**Comment by Ifera** [comment] 2020-04-05 17:54
Mind sending that error?

**Comment by minijaham** [comment] 2020-04-06 17:54
How do I send the error? Sorry...

**Comment by Ifera** [comment] 2020-04-08 09:02
Copy paste

**Comment by minijaham** [comment] 2020-04-09 22:36
Where can I get the error? Just copy what it says in the UI when the error occurs?

**Comment by Thunder33345** [comment] 2020-04-10 12:04
what it says on the console

**Comment by minijaham** [comment] 2020-04-10 20:16
It doesn't say anything in the console. Just this when I have integer named house set
[](https://cdn.discordapp.com/attachments/636021824605650958/698265002158588004/unknown.png)

**Comment by minijaham** [comment] 2020-04-10 20:16
Go to this link:
https://cdn.discordapp.com/attachments/636021824605650958/698265002158588004/unknown.png

**Comment by Ifera** [comment] 2020-04-22 04:45
Can you give the steps to reproduce this issue?

**Comment by minijaham** [comment] 2020-04-23 19:47
1. Download the plugin to /plugins folder 
2. Go in-game, and execute /home set 1(or anything that includes a number in it)
3. Do /home and click on "Teleport"
4. You should see the picture

**Comment by Ifera** [comment] 2020-05-01 13:37
will take a look at it later today

**Comment by minijaham** [comment] 2020-05-02 18:58
:)

**Comment by Ifera** [comment] 2020-05-03 20:02
Okay so it turns out that this bug was indeed fixed in #5 but lazy me never submitted a new release to poggit. Try using the latest dev build, this bug doesnt appear since I just tested it. I have submitted an updated release to poggit tho.

**Closed as completed by Ifera** 2020-05-03 20:02 UTC

**Comment by Ifera** [comment] 2020-05-03 20:14
Actually.. Now i remember why I never submitted a new release.. it was because I wanted to implement #4 before submitting a new release..
